---
- hosts: localhost
  name: Create webvol on svm1 to host html files for webserver
  vars:
    login: &login   
     hostname: 192.168.0.101
     username: admin
     password: Netapp1!
     https: true
     validate_certs: false
    vserver: svm1
    aggr: aggr1_cluster1_01_data
    vol_name: webvol
    policy: ansible
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      junction_path: "/{{ vol_name }}"
      size: 10
      size_unit: gb
      policy: "{{ policy }}"
      space_guarantee: none
      volume_security_style: unix
      <<: *login
- hosts: nginx
  become: true
  vars:
    packages:
     - epel-release
     - nginx
    vol_name: webvol
    nfs_lif : 192.168.0.131  
  tasks:
  - name: Add epel-release repo and install nginx
    yum:
     name: "{{ packages }}"
     state: latest
  - name: Mount webvol as /usr/share/nginx/html/
    mount:
     name: /usr/share/nginx/html/
     src: "{{ nfs_lif }}:/{{ vol_name }}"
     fstype: nfs
     state: mounted
  - name: Copy HTML Workshop Index Page to the webvol
    template:
      src: index.html
      dest: /usr/share/nginx/html/index.html
  - name: Update NGiNGX Config to use port 8080
    template:
      src: nginx.conf
      dest: /etc/nginx/nginx.conf
  - name: Start NGiNX
    service:
      name: nginx
      state: started
