---
- hosts: servers
  name: Mount "ansibleVol" on both rhel hosts
  vars:
    vol_name: ansibleVol
    nfs_lif : 192.168.0.131
  tasks:
  - name: Creates directory
    file:
     path: "/mnt/{{ vol_name }}"
     state: directory
  - name: Mount ansibleVol as /mnt/ansibleVol
    mount:
     name: "/mnt/{{ vol_name }}"
     src: "{{ nfs_lif }}:/{{ vol_name }}"
     fstype: nfs
     state: mounted
