---
- hosts: localhost
  gather_facts: false
  name: NetApp add licenses on cluster1
  vars:
    login: &login
     hostname: 192.168.0.101 # NetApp Cluster IP
     username: admin # Cluster User
     password: Netapp1! # Cluster Password
     https: true
     validate_certs: false
  tasks:
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      license_code: YXXXXKDBHKPKICAAAAAAAAAAAAAA
      <<: *login
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      license_code: KXXXXKDBHKPKICAAAAAAAAAAAAAA
      <<: *login
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      license_code: WXXXXKDBHKPKICAAAAAAAAAAAAAA
      <<: *login
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      license_code: IXXXXKDBHKPKICAAAAAAAAAAAAAA
      <<: *login
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      license_code: GXXXXKDBHKPKICAAAAAAAAAAAAAA
      <<: *login
  - name: Install Licenses
    na_ontap_cluster:
      state: present
      license_code: SXXXXKDBHKPKICAAAAAAAAAAAAAA
      <<: *login