---
- name: create volume
  hosts: localhost
  vars:
    hostname: 192.168.0.101
    username: admin
    password: Netapp1!
    vserver: svm1
    volname: ansibleVol
  tasks:
  - name: create volume
    na_ontap_volume:
      state: present
      name: "{{ volname }}"
      aggregate_name: aggr1_cluster1_01_data
      size: 100
      size_unit: mb
      vserver: "{{ vserver }}"
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false
