---
- name: create volume
  hosts: localhost
  tasks:
  - name: create volume
    na_ontap_volume:
      state: present
      name: ansibleVol
      aggregate_name: aggr1_cluster1_01_data
      size: 100
      size_unit: mb
      vserver: svm1
      hostname: 192.168.0.101
      username: admin
      password: Netapp1!
      https: true
      validate_certs: false
