---
- name: create volume
  hosts: localhost
  vars:
    login: &login
     hostname: "{{ hostname }}"
     username: "{{ username }}"
     password: "{{ password }}"
     https: true
     validate_certs: false
  vars_files:
  - var_vol5.yml
  tasks:
  - name: create volume
    na_ontap_volume:
      state: present
      name: "{{ item.name }}"
      aggregate_name: "{{ item.aggr }}"
      size: "{{ item.size }}"
      vserver: "{{ item.vserver }}"
      size_unit: mb
      <<: *login
    with_items: "{{ vol }}"
